# FROM line stays the same
FROM python:3.11.13-slim

WORKDIR /app

# COPY from relative path inside the build context
COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
